version: "3.7"

services:
  compute-api:
    build: .
    ports:
      - 5000:5000
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=${HOSTNAME:-nuvlabox}


