version: "3.7"

services:
  agent:
    build: .
    ports:
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NUVLABOX_ID=<placeholder>
      - HOST=$(hostname)


